version: "3.8"

services:
  master_controller:
    build: .
    image: <image_name>
    container_name: icarus_master_controller
    ports:
      - "8097:8097"

    env_file:
      - env/master-controller.env
    networks:
      - icarus-backend-network
    logging:
      options:
        max-size: "5m"
        max-file: "5"
    command: bash -c "java -Xms256M -Xmx3072M -jar master_controller.jar"

networks:
  icarus-backend-network:
    name: icarus-backend-network
    driver: bridge
